spring.application.name=ticket-pool-simulation
spring.data.mongodb.uri=mongodb+srv://Hariraam:hariraam@ticketingapplication.uvnb9.mongodb.net/?retryWrites=true&w=majority&appName=TicketingApplication
spring.data.mongodb.database=Ticket